# Generated by Django 3.2.3 on 2021-05-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='b_id',
            new_name='bank',
        ),
    ]
